---
title: "EPPS Math and Coding Camp"
subtitle: "Day 1_2: Symbols and Notations"
author: "Instructor: Azharul Islam"
format: 
  revealjs:
    theme: [serif, custom.scss]
    slide-number: true
    logo: eppslogo.png
    css: logo.css
editor: visual
---

## Introduction

Math is a formal language useful in conveying and understanding concepts. In particular, it helps in explaining connections between concepts. In this session, we set out to review how to read mathematical symbols and notations.

## Common Sets

$$
\begin{array}{|c|c|}
\hline
\text{Notation} & \text{Meaning} \\
\hline
\mathbb{N} & \text{Natural numbers} \\
\mathbb{Z} & \text{Integers} \\
\mathbb{Q} & \text{Rational numbers} \\
\mathbb{R} & \text{Real (rational and irrational) numbers} \\
\mathbb{C} & \text{Complex numbers} \\
\mathbb{N}_+ & \text{Positive values of the set} \\
\mathbb{N}^d & \text{Dimensionality (number of dimensions)} \\
\hline
\end{array}
$$

## Commonly Used Symbols and Notations

$$ 
{\scriptsize
\begin{array}{|c|c|c|c|}
\hline
\text{Symbol} & \text{Meaning} & \text{Symbol} & \text{Meaning} \\
\hline
a, b, x, y & \text{Variables, Constants} & \cup & \text{Union} \\
f, g, h & \text{Functions} & \cap & \text{Intersection} \\
n, m, k & \text{Integers} & \setminus & \text{Set difference} \\
i, j & \text{Indices} & \emptyset & \text{Empty set} \\
x_i & \text{Element of sequence or set} & \forall & \text{For all, for each, for every} \\
\in & \text{Element of} & \exists & \text{There exists} \\
\notin & \text{Not an element of} & \neg & \text{Negation (not)} \\
\subset & \text{Subset} & \wedge & \text{Logical AND} \\
\subseteq & \text{Subset or equal} & \vee & \text{Logical OR} \\
|a| & \text{Absolute value} & \implies & \text{Implies} \\
a! & \text{Factorial} & \iff & \text{If and only if} \\
\sum & \text{Summation} & \prod & \text{Product} \\
\hline
\end{array}
}
$$

## Basic Arithmetic Operations

### Addition and Subtraction

-   $a + b$: Addition of $a$ and $b$
-   $a - b$: Subtraction of $b$ from $a$

------------------------------------------------------------------------

## Multiplication and Division

### Multiplication

-   $a \cdot b$ or $a \times b$: Multiplication of $a$ and $b$
-   $ab$: Multiplication of $a$ and $b$ when implied by juxtaposition

### Division

-   $a / b$: Division of $a$ by $b$
-   $\frac{a}{b}$: Division of $a$ by $b$

------------------------------------------------------------------------

## Exponents and Roots

### Exponents

-   $a^b$: $a$ raised to the power of $b$
-   $a^2$: $a$ squared
-   $a^3$: $a$ cubed

### Roots

-   $\sqrt{a}$: Square root of $a$
-   $\sqrt[n]{a}$: $n$-th root of $a$

------------------------------------------------------------------------

## Summation and Product Notation

### Summation

-   $\sum_{i=1}^{n} a_i$: Summation of $a_i$ from $i=1$ to $i=n$

### Product

-   $\prod_{i=1}^{n} a_i$: Product of $a_i$ from $i=1$ to $i=n$

------------------------------------------------------------------------

## Set Operations

### Union and Intersection

-   $A \cup B$: Union of sets $A$ and $B$
-   $A \cap B$: Intersection of sets $A$ and $B$

### Difference

-   $A \setminus B$: Difference of sets $A$ and $B$

------------------------------------------------------------------------

## Logical Operations

### Logical AND, OR, and NOT

-   $A \wedge B$: Logical AND of $A$ and $B$
-   $A \vee B$: Logical OR of $A$ and $B$
-   $\neg A$: Logical NOT of $A$

------------------------------------------------------------------------

## Other Common Symbols

### Absolute Value and Factorials

-   $|a|$: Absolute value of $a$
-   $a!$: Factorial of $a$

### Inequality

-   $a < b$: $a$ is less than $b$
-   $a > b$: $a$ is greater than $b$
-   $a \leq b$: $a$ is less than or equal to $b$
-   $a \geq b$: $a$ is greater than or equal to $b$

------------------------------------------------------------------------

## Mathematical Constants

### Constants

-   $\pi$: Pi, the ratio of the circumference of a circle to its diameter
-   $e$: The base of the natural logarithm, approximately equal to 2.71828

------------------------------------------------------------------------

## Cartesian Products and Intervals

### Cartesian Products

-   $A \times B$: Cartesian product of sets $A$ and $B$

### Intervals

-   $(a, b)$: Open interval from $a$ to $b$
-   $[a, b]$: Closed interval from $a$ to $b$
-   $(a, b]$: Half-open interval from $a$ to $b$, including $b$ but not $a$
-   $[a, b)$: Half-open interval from $a$ to $b$, including $a$ but not $b$

## Quantifiers and Logical Connectives

### Universal and Existential Quantifiers

-   $\forall x$: For all (or for every or for each) $x$
-   $\exists x$: There exists $x$

### Implication and Biconditional

-   $A \implies B$: $A$ implies $B$
-   $A \iff B$: $A$ if and only if $B$

### Negation

-   $\neg C$: Negation (not $C$)
